spring:
  application:
    name: "gatewayserver"
  config:
    import: optional:configserver:http://localhost:8097/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8096


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gatewayserver Application"
    version: "1.0.0"